version: "3.3"

services:
  box-hg-gateway:
    image: "EnglishAPI-homolog:${CODE_SC_HG}"
    ports:
      - 8380:80
    environment:
      - nome.ambiente=Homologação
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

        