version: "3.3"

services:
  box-hg-gateway:
    image: "englishapi"
    ports:
      - 8380:8080
    environment:
      - nome.ambiente=Homologação
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
